### ISSUE TITLE
Two negative geo mean columns

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#105]
Negative geo mean is calculated and saved to the object twice. 
1. At segment qc
2. At count aggregation after probe QC

Once probe qc is performed the original negative geo mean should be removed or we remove the initial column altogether with negative geometric mean only being saved to the object after probe qc.

@JasonWReeves out of these two solutions which one makes the most sense?

**Comment by NicoleEO** [comment]
@JasonWReeves - I need to remove the first geomean altogether. It isn't used anywhere and would be incorrect for the user to use downstream.

**Comment by JasonWReeves** [comment]
@NicoleEO agreed - count aggregate is when the two columns are needed. We would ideally not calculate LOQ until after the outliers are removed

**Comment by NicoleEO** [comment]
Fixed in https://github.com/Nanostring-Biostats/GeomxTools/commit/c5bb3696339e8f170e3f6e0fb2183d79111d2e77
