### ISSUE TITLE
Test Cases Needed

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#107]
- [x] Test for summarizenegs
- [x] Test for setsegmentqcflags matches the qc after all other segment QC set
- [x] Test that if no nuclei or area does not perform those qc without error
- [x] Add test Spec 3 for probe qc, targs with less than 3 probes get no grubbs flags
- [x] #115
- [x] checkQCFlags test (pushed back a release)
- [x] all utils functions need test
- [x] add countsshiftedbyone to accessors test cases (#109)
- [x] when the feature type is "Target"
- [x] check error message in agg counts when there are not "Negatives"
- [x] check error message in agg counts when there are not multiprobe targets
- [x] Add tests to check single probe counts are correctly handled in agg
- [x] Update test for rewritten background subtraction function (#110)

GxT v. DA script to be added as attachment in QB:
- [x] Test results match for segment QC
- [x] Test results match for probe QC

**Comment by maddygriz** [comment]
Test cases for DA comparison were added in a separate test file and added to quickbase
