### ISSUE TITLE
Background subtraction needs testing

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#110]
Background subtraction needs to be tested:

- [x] Does it work
- [x] Does it work correctly with multiple panels (subtract negs from the corresponding panel targets)
- [x] Is the test working and complete (resolving in issue #107)

**Comment by johnyaku** [comment]
We are looking at background removal for our data.
If you can point me to the appropriate branch/function/documentation I'll give you some feedback.
