### ISSUE TITLE
Excel column types

### ISSUE THREAD

**Issue by johnyaku** [Nanostring-Biostats/GeomxTools#111]
`readNanoStringGeomxSet()` ingests numeric columns from the annotation Excel file (`phenoDataFile`) as "character" if the column contains non-numeric values such as "NA".

Suggestion: either add an `na` parameter and pass it on to `readxl::read_xlsx` (line 30, dev branch) or use `...` to pass arbitrary options (such as `col_types`) down to `readxl::read_xlsx` to give the user greater control as to how data is ingested.

**Comment by NicoleEO** [comment]
Great suggestion. We will get this included for the next release.

**Comment by NicoleEO** [comment]
@johnyaku I've incorporated this update here: https://github.com/Nanostring-Biostats/GeomxTools/tree/iss111-xlops
This should get included as of version 1.1.3.
