### ISSUE TITLE
Add check for RTS ID overlap

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#13]
Per Erin RTS IDs should not overlap between different panel pkcs. This should be checked though and I'm assuming a stop placed in or a warning with a relabel of the RTS ID as is done with the target names.

**Comment by NicoleEO** [comment]
Issue is not in where the duplication resolution occurs in readPKCfile, but instead how would resolve counts to these duplicated probes in the pkc. There is a question as to how this would even be resolved or if this situation is even possible. The dcc files would never have duplicate RTS IDs. This is only possible in the pkc file. Solution:
1. Check to make sure they are truly duplicate entries in the pkc file and remove the 
extra row.
2. If these are different entries, we cannot accurately assign to the correct pkc entry, therefore, pkc read should error and the analysis should be aborted with a message saying to contact support/recheck that they have used an unaltered pkc file.

**Comment by piazze2** [comment]
Hi Nicole,

If I’m following you, the question is asking whether or not it’s possible to have a duplicate RTS ID in a PKC? No, it is not. This is something checked by the script that generates these. PKC generation would be aborted if a duplicate were identified.

Erin

**Comment by NicoleEO** [comment]
@piazze2 fabulous. That negates the need for this issue. Thanks!!
