### ISSUE TITLE
Documentation on `annotation.xlsx` input file

### ISSUE THREAD

**Issue by jvivian-atreca** [Nanostring-Biostats/GeomxTools#134]
Hi dev team,

Thank you for your work on this package. I am hoping to use it to automate the generation of the output `initial dataset.xlsx` we would get from manually going through the DSP portal options.

I have been unable to locate information pertaining to `annotation.xlsx` file that is required input to generate the `demoData` object in the vignette, both in the stable and dev release (1.99.4):

```R
demoData <-
    suppressWarnings(readNanoStringGeoMxSet(dccFiles = DCCFiles,
                                            pkcFiles = PKCFiles,
                                            phenoDataFile = SampleAnnotationFile,
                                            phenoDataSheet = "test",
                                            phenoDataDccColName = "Sample_ID",
                                            protocolDataColNames = c("aoi",
                                                                     "cell_line",
                                                                     "roi_rep",
                                                                     "pool_rep",
                                                                     "slide_rep")))
```

I asked the wet lab team operating the Nanostring and their response was:

> I have not seen this before, neither the sample file nor the lab worksheet look anything like this.

Based on the example data, I was able to proxy the file to generate the object by deriving the `Sample_ID` from the DCC filenames, but the documentation does not describe which other columns are required nor defines them. I got an indexing error if `protocolDataColNames` was left `NULL`, so I tried to proxy those columns as best I could.

1. Is detailed information about the `annotation.xlsx` file located somewhere else?
2. Which columns impact how the integer counts are calculated? I adjusted the values and didn't see it reflect changes in the counts. If I were more familiar with R debugging I would try and answer this myself, sorry.
3. I am a bit unclear how to map the DSP segments, such as those in the `initial dataset.xlsx`, (typically of the form **Sample - Region - ROI**) to the individual DCC files. More information on that would also be much appreciated.

Thank you again!

Cheers,
John

**Comment by NicoleEO** [comment]
Hi John,

Great questions. We just released a new workflow vignette to help people get started. It includes the description of what the inputs are as well as examples of running through an RNA NGS experiment using the GeomxTools package: https://bioconductor.org/packages/release/workflows/html/GeoMxWorkflows.html. If you have any additional questions, please let us know. I will add a link to the workflow in the GeomxTools readme for future users as well.

Thank you,
Nicole

**Comment by jvivian-atreca** [comment]
@NicoleEO — Thank you so much for the expeditious response!

**Comment by jvivian-atreca** [comment]
Hi @NicoleEO — I checked the `package.version` for latest stable release and it said "2.0.0" - is that the right version? I don't see any additional information on the annotations file than what I saw in the 1.99.4 release. Is there somewhere I can learn specifically how columns like `roi_rep`, `pool_rep`, `slide_rep` are defined? 

Based on the DCC files and `roi_rep` information, it looks like I would need to aggregate or average the counts between roi_reps when mapping them to the segment level, is that assumption correct?

**Comment by NicoleEO** [comment]
Hi John - These `_rep` columns were manually entered by the scientist for easy comparison between samples. These columns are specific for this dataset so you do not need to recapitulate. It is intended that you would update the `readNanoStringGeomxSet()` call to fit your annotation file. You can use `??readNanoStringGeoMxSet` to pull up the help documentation for this function. 

I am resending you the link to the workflow. This is a separate package from GeomxTools. I would start with this vignette and not the one attached to the GeomxTools package. https://www.bioconductor.org/packages/release/workflows/vignettes/GeoMxWorkflows/inst/doc/GeomxTools_RNA-NGS_Analysis.html

Note, start from the lab worksheet from your study readout package to create your annotation file. You can add as many sample annotation columns to the lab worksheet as you like to organize your samples by. I do have a couple of caveats to manually adding annotations. 1) Do not change the order of the samples from the lab worksheet. 2) Do not change the column names that come with the default lab worksheet. 

If you need help understanding your lab worksheet, study readout files, and experimental parameters, please contact geomxsupport@nanostring.com.

Thanks,
Nicole

**Comment by NicoleEO** [comment]
@jvivian-atreca checking in to see if the above response answered your questions about the GeomxTools package?

**Comment by jvivian-atreca** [comment]
Hi @NicoleEO — Apologies, I was OOO last week. Your explanation is very helpful, thank you!
