### ISSUE TITLE
Error: object ‘featureType’ is not exported by 'namespace:GeomxTools'

### ISSUE THREAD

**Issue by avrobullet** [Nanostring-Biostats/GeomxTools#135]
Hey Nicole,

I'm working with my colleagues to merge the GeoDiff code they created with the pipeline, however we noticed that GeomxTools does not have `featureType` exported in the package's namespace. The GeoDiff package given to us to review and work on calls for this object from GeomxTools.

Cheers,

Alex

**Comment by NicoleEO** [comment]
@avrobullet - It looks like featureType is an exported method: https://github.com/Nanostring-Biostats/GeomxTools/blob/97959d5f38eb07b3bab380e5b82048ae368d3f72/NAMESPACE#L54 Can you post your sessionInfo(), an mwe, and the error you are getting?
Thanks - Nicole

**Comment by avrobullet** [comment]
For sure.

`...
installing to /Library/Frameworks/R.framework/Versions/4.1/Resources/library/00LOCK-GeoDiff/00new/GeoDiff/libs
** R
** data
** byte-compile and prepare package for lazy loading
Error: object ‘featureType’ is not exported by 'namespace:GeomxTools'
Execution halted
ERROR: lazy loading failed for package ‘GeoDiff’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/GeoDiff’
Error: $ operator is invalid for atomic vectors
In addition: Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/ws/0sd6bdkn4qv2lq75j0t50shc0000gn/T//Rtmp0h19H5/filee01d3f1befea/GeoDiff_0.99.5.tar.gz’ had non-zero exit status
2: In FUN(X[[i]], ...) : no package 'GeoDiff' was found`

**Comment by NicoleEO** [comment]
The library being used to build GeoDiff is most likely an old version. I would navigate to your library directory this is pulling from and check the version numbers of the packages. Or just refresh them to the latest versions for both NanoStringNCTools and GeomxTools.
https://bioconductor.org/packages/release/bioc/html/NanoStringNCTools.html
https://bioconductor.org/packages/release/bioc/html/GeomxTools.html

**Comment by NicoleEO** [comment]
Hi @avrobullet. Can you confirm this solved your issue? Thanks, Nicole

**Comment by GWMcElfresh** [comment]
Hi all. I had this error pop up as well. The fix for me was updating from the BioConductor version of GeomxTools to the dev version on github. 

Thanks!

**Comment by NicoleEO** [comment]
@GWMcElfresh can you confirm if your bioconductor version was installed recently?

**Comment by GWMcElfresh** [comment]
@NicoleEO  Yeah, I started working with the vignettes today without having worked on a related project previously. Installed via `BiocManager::install("GeomxTools")`

**Comment by NicoleEO** [comment]
Thanks for confirming @GWMcElfresh. It must have to do with the Bioconductor installation method as the package code is the same in both repos.
