### ISSUE TITLE
Write Normalization functions for GeomxTools

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/GeomxTools#15]
Write normalization module for GeomxTools
 
NanoStringGeomxSet-normalize.R modularize based on object and data type. Calls specific .R file for each data_type = c(RNA, protein)
and norm method = NGS normalization Q3 normalization Background norm Lei's method Area or nuclei scaling norm
For protein: norm_method = Housekeeper norm IgG norm area norm

Example:

setGeneric("normalize", signature=c("object", "norm_method"), function(object, norm_method, data_type, ...) standardGeneric("normalize"))

setMethod("normalize", c("NanoStringGeomxSet", "Q3"),
function(object, norm_method, data_type="RNA", ...) { run_Q3(object, data_type) })

setMethod("normalize",c("NanoStringGeomxSet", "Lei_mod") ,
function(object, norm_method, data_type="RNA", ...) { run_Lei(object, data_type) })

setMethod("normalize",c("NanoStringGeomxSet", "neg_norm") ,
function(object, norm_method, data_type="RNA", ...) { run_neg_norm(object, data_type) })

setGeneric("run_Q3", signature= "data_type"), function(object, data_type) standardGeneric("normalize"))

setMethod("run_Q3", "RNA"), function(object, data_type) { #RNA Q3 norm steps })

**Comment by rvitancol** [comment]
- [ ] Write Neg Norm for RNA
- [ ] Add quantile as argument to qnorm
- [ ] Add roxygen

**Comment by rvitancol** [comment]
- [ ] Check nomalization for protein data

**Comment by NicoleEO** [comment]
Included in 2.99.2
