### ISSUE TITLE
Bioc 3.15 Checks

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#160]
Warnings:
- [x] Undocumented code objects:
  ‘as.Seurat’
Timeout:
- [x] Examples and probably tests running long on mac build. This might resolve on its own tomorrow, but just in case maybe considering trimming the test and example data down.
![image](https://user-images.githubusercontent.com/20404635/164075585-4f0355c6-0cd9-4f64-bd71-030520da6bd9.png)

**Comment by maddygriz** [comment]
With updated example & test code:
   - vignettes = 4m 23.2s
   - examples = 3m 2.9s
   - tests = 7m 25.7s
