### ISSUE TITLE
Issue with DCC files. 

### ISSUE THREAD

**Issue by ClaudiaZagami** [Nanostring-Biostats/GeomxTools#165]
Hi! I am approaching to the use of the package and I have to say that I am not an expert in bioinformatics (just learning now with my new geomx data). I have problems in the very first step, I keep getting an error "Error in readNanoStringGeoMxSet(dccFiles = DCC_directory, pkcFiles = PKCFiles,  : 
  Specify valid dcc files." 
I checked the path several times and the files but it still do not work. Do you have any suggestion of what I can do to fix the issue? Sorry for the very naive question but as I said I am at my "familiarisation" step"! 
Thank you a lot. 
Best wishes.

**Comment by NicoleEO** [comment]
@danielnewhouse and @fnew, can you help Claudia with the above issue?

**Comment by danielnewhouse** [comment]
@ClaudiaZagami Could you share the code used to create  the DCC_directory and the readNanoStringGeoMxSet?

**Comment by ClaudiaZagami** [comment]
Hi Nicole and Dianel, 
Thank you for your kind answer. 
Please, find here the code:

setwd("C:/Users/czagami/NanostringData")
directory <- "C:/Users/czagami/NanostringData"
DCC_directory <- "C:/Users/czagami/NanostringData/GeoMxNGS_Pipeline_Requeue_Normal_samples_CZ_DCC"

DCCFiles <- file.path(DCC_directory, pattern=".dcc$", full.names=TRUE)

PKCFiles <- file.path(directory, "Hs_R_NGS_WTA_v1.0.pkc")

SampleAnnotationFile <- file.path(directory, "Annotation_file3 - final.xlsx")

#I do not understand why it does not recognise the files. 
myData <- readNanoStringGeoMxSet(dccFiles = DCCFiles,
                                          pkcFiles = PKCFiles,
                                          phenoDataFile = SampleAnnotationFile,
                                          phenoDataSheet = "Annotation template")

Thanks. 
Claudia

**Comment by danielnewhouse** [comment]
> I am also trying to use the other package and the error is different and it is about the sample annotation file now. the error is "Error: `path` must be a string"

Check the `SampleAnnotationFile` out to see if there is a single path listed:
![image](https://user-images.githubusercontent.com/26310608/165993377-c82d74ac-0abf-486d-a43a-5866aa8153aa.png)

Or if there are multiple paths listed:
![image](https://user-images.githubusercontent.com/26310608/165993599-5136fbbb-85ef-448b-a011-5a9e8a0bb0d7.png)

The error you received will happen if there are multiple paths listed in `SampleAnnotationFile`. Your directory may have multiple Excel files. Alternatively, if there is a single Excel file in the directory, if the file was open in another program (like Excel) when you run the command, R may read in a hidden temporary file that Windows created. I suggest checking your `SampleAnnotationFile` output and selecting the proper file with e.g. `SampleAnnotationFile[1]`.

**Comment by ClaudiaZagami** [comment]
Hi Danel, 
Thank you so much for your help. 
The code is running now, I found the problem with the excel files and also I was missing the correspondence with the DDC files. 

I have now a problem in the normalisation. 
in this step # Graph Q3 value vs negGeoMean of Negatives

I have an error: Error in `[.data.frame`(pData(target_myData), , ann_of_interest) : 
  undefined columns selected

I am trying to understand which are the unspecified columns but I am not changin much of the code so it should be running theoretically but it doesn't. 
This is what I get if I command traceback()

> traceback()
4: stop("undefined columns selected")
3: `[.data.frame`(pData(target_myData), , ann_of_interest)
2: pData(target_myData)[, ann_of_interest]
1: data.frame(row.names = colnames(exprs(target_myData)), Segment = colnames(exprs(target_myData)), 
       Annotation = pData(target_myData)[, ann_of_interest], Q3 = unlist(apply(exprs(target_myData), 
           2, quantile, 0.75, na.rm = TRUE)), NegProbe = exprs(target_myData)[neg_probes, 
           ])

can you help me with this? 
Thank you so much. 
Claudia
