### ISSUE TITLE
error using as.Seurat

### ISSUE THREAD

**Issue by yupingz** [Nanostring-Biostats/GeomxTools#176]
Hi,

Thank you for making this tool. I have problem using the Coercion of GeoMxSet to Seurat function. I could not figure out why as.Seurat didn't work for me. I was running the testing code. Any insight what was wrong?

> library(GeomxTools)
> datadir <- system.file("extdata", "DSP_NGS_Example_Data", package = "GeomxTools")
> demoData <- readRDS(file.path(datadir, "/demoData.rds"))
> target_demoData <- aggregateCounts(demoData[1:1000,1:10])
Warning message:
In aggregateCounts(demoData[1:1000, 1:10]) :
  Object has no negatives. No summary statistics for negatives will be calculated.
> target_demoData <- normalize(target_demoData, "quant")
> seurat_demoData <- as.Seurat(target_demoData, ident = "cell_line",
                              normData = "exprs_norm", forceRaw = FALSE)
Error in UseMethod(generic = "as.Seurat", object = x) : 
  no applicable method for 'as.Seurat' applied to an object of class "c('NanoStringGeoMxSet', 'NanoStringRccSet', 'ExpressionSet', 'eSet', 'VersionedBiobase', 'Versioned')"
> packageVersion("GeomxTools")
[1] ‘3.0.1’

**Comment by NicoleEO** [comment]
Hi @yupingz,

Thank you for reaching out. Our customer support team will be able to help you with this. Please email [geomxsupport@nanostring.com](mailto:geomxsupport@nanostring.com) with your issue.

Thanks,
Nicole

**Comment by LuShuYangMing** [comment]
Also got the error information from as.Seurat function:
`
DSP <- GeomxTools::as.Seurat(sce,normData = "q_norm")
Registered S3 methods overwritten by 'Seurat':
  method                     from        
  $.JackStrawData            SeuratObject
  $.Seurat                   SeuratObject
  $.SeuratCommand            SeuratObject
  $<-.Seurat                 SeuratObject
  [.Assay                    SeuratObject
  [.DimReduc                 SeuratObject
  [.Seurat                   SeuratObject
  [.SeuratCommand            SeuratObject
  [[.Assay                   SeuratObject
  [[.DimReduc                SeuratObject
  [[.Seurat                  SeuratObject
  levels<-.Seurat            SeuratObject
  .DollarNames.JackStrawData SeuratObject
  .DollarNames.Seurat        SeuratObject
  .DollarNames.SeuratCommand SeuratObject
  as.list.SeuratCommand      SeuratObject
  as.logical.JackStrawData   SeuratObject
  dim.Assay                  SeuratObject
  dim.DimReduc               SeuratObject
  dim.Seurat                 SeuratObject
  dimnames.Assay             SeuratObject
  dimnames.DimReduc          SeuratObject
  dimnames.Seurat            SeuratObject
  droplevels.Seurat          SeuratObject
  length.DimReduc            SeuratObject
  levels.Seurat              SeuratObject
  merge.Assay                SeuratObject
  merge.Seurat               SeuratObject
  names.DimReduc             SeuratObject
  names.Seurat               SeuratObject
  print.DimReduc             SeuratObject
  subset.Assay               SeuratObject
  subset.DimReduc            SeuratObject
  subset.Seurat              SeuratObject
Error in `[[<-`(`*tmp*`, "orig.ident", value = idents) : 
  [[<- defined for objects of type "S4" only for subclasses of environment`

**Comment by maddygriz** [comment]
Hi @LuShuYangMing ,

Thank you for reaching out. Our customer support team will be able to help you with this. Please email [geomxsupport@nanostring.com](mailto:geomxsupport@nanostring.com) with your issue.

Thanks,
Maddy
