### ISSUE TITLE
The differences of QC parameter between Rpackage and GeoMx DSP software

### ISSUE THREAD

**Issue by thecatgonewithwid** [Nanostring-Biostats/GeomxTools#177]
Hi,i used to run DSP QC on GeoMx DSP software(version 2.2.0.111) ,and i have noticed some differences of QC parameter default-thredhold between Rpackges and software Like minNuclei and minArea.

Software thredhold:
minNuclei = 200 , minArea =  16000

Rpackage thredhold:
minNuclei = 16000 , minArea =  20

Why is the difference so great?

**Comment by NicoleEO** [comment]
Hi @thecatgonewithwid,

Thank you for reaching out. Our customer support team will be able to help you with this. Please email [geomxsupport@nanostring.com](mailto:geomxsupport@nanostring.com) with your issue.

Thanks,
Nicole
