### ISSUE TITLE
Combining experiments

### ISSUE THREAD

**Issue by Pointillomic** [Nanostring-Biostats/GeomxTools#183]
Hello,

Thank you for making such a useful tool to access and analyze GeoMX data!

I was wondering if there was a way to combine data across experiments. A lot of the tools for normalization and QC are based on the NanoStringGeoMxSet data structure, and I wanted to combine different experiments to normalize and compare results across different experiments

Any help with this would be greatly appreciated!

**Comment by maddygriz** [comment]
Hi @Pointillomic, 

I'm glad you find the package useful. 

Thank you for reaching out. Our customer support team will be able to help you with this. Please email [support@nanostring.com](mailto:support@nanostring.com) with your issue.

Thanks,
Maddy

**Comment by rikizad** [comment]
Hi
I'm leaving the response from support here in case anyone else needs it: 
"To combine data from multiple GeoMx experiments, you can combine the lab worksheets and place all DCC files into one folder. To combine lab worksheets, open the .txt files in Excel, remove the excess header rows, and copy paste the contents of the two (or more) lab worksheets into one .xlsx file. When you run GeoMxTools, you can point the readNanoStringGeoMxSet() function to the combined labworksheet and folder with all of the DCC files. This will load one unified GeoMxSet object."
