### ISSUE TITLE
Error in readNanoStringGeoMxSet() arguments imply differing number of rows

### ISSUE THREAD

**Issue by emilylasse** [Nanostring-Biostats/GeomxTools#188]
I'm getting an error after running the following code:

## loading data and creating data object
DCCFiles <- list.files("~/Desktop/Spatial/8027-EL_GeoMxQC_results/DCC-20230622", full.names = T, pattern = ".dcc$")
PKCFiles <- file.path("~/Desktop/Spatial/8027-EL_GeoMxQC_results/InputData/Hs_R_NGS_WTA_v1.0.pkc")
SampleAnnotationFile <- ("~/Desktop/Spatial/8027-EL_GeoMxQC_results/curated_annotations_July2023.xlsx")

ns_object <-readNanoStringGeoMxSet(dccFiles = DCCFiles,
                         pkcFiles = PKCFiles,
                         phenoDataFile = SampleAnnotationFile,
                         phenoDataSheet = "Sheet1",
                         phenoDataDccColName = "Sample_ID",
                         experimentDataColNames = c("panel"))

Error in data.frame(..., check.names = FALSE) :                                                             
  arguments imply differing number of rows: 125, 2

Can anyone help me correct the code?

**Comment by NicoleEO** [comment]
Hi @emilylasse,

Thank you for reaching out. Our customer support team will be able to help you with this. Please email support@nanostring.com with your issue.

Thanks,
Nicole

**Comment by emilylasse** [comment]
Sounds good - thanks!
