### ISSUE TITLE
Local outlier speed up

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#20]
The time for local outlier testing is long. Consider testing/adding:

- [x] Optimal structure and methods
- [x] Trim to those that have at least 3 probes
- [x] Trimming to those that only pass min count
- [ ] parallelizing
- [x] Add rox comments

**Comment by rvitancol** [comment]
tried the QC but the object becomes too heavy with all the outlier flags. Let's keep this in mind when solving this issue.
![image](https://user-images.githubusercontent.com/55164869/108098296-0e941f80-7038-11eb-9229-2e17802f9688.png)
