### ISSUE TITLE
vignette method not working

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#26]
Calling vignette(package="GeomxTools") in dev container and "no vignette found" pops up. Need to ensure this is available to users through the normal channels.

If this is a devtools issue, need to add note to install instructions so users know it won't show.

**Comment by zhiiiyang** [comment]
It is working on the PC. 

![image](https://user-images.githubusercontent.com/7269113/108432573-79d91f80-71f9-11eb-86ff-5b7e7033f139.png)
![image](https://user-images.githubusercontent.com/7269113/108432607-82c9f100-71f9-11eb-95c8-e3d02039d9e2.png)

**Comment by NicoleEO** [comment]
@zhiiiyang hmmm I wonder if this is a devtools install issue. I think I remember something about that.

**Comment by zhiiiyang** [comment]
@NicoleEO, very likely.

**Comment by NicoleEO** [comment]
I confirmed this is devtools install user error. Need to set build_vignettes to TRUE for devtool install.
