### ISSUE TITLE
Functions I'd like to see in GeoMxTools (QC and normalization)

### ISSUE THREAD

**Issue by patrickjdanaher** [Nanostring-Biostats/GeomxTools#29]
Here's a partial list of nice-to-have features for GeoMxTools

NGS readout normalization functions:
- [x] Scale to a user-selected quantile of the data
- [x] Subtract background from a data matrix
- [x] One preferred normalization approach: background subtract, then calculate quantiles, then scale the background-subtracted data to quantiles. (This would only support linear-scale analyses.)
- [x] Another preferred normalization approach: scale to a quantile like Q9 then log2-transform

QC plots:
- [x] A plot to flag AOIs with low outlier signal strength. A simple histogram of signal strength (as measured by a given normalization factor) would suffice. 
- [x] Kara's raw data QC heatmap
- [x] A spaceplot showing the AOI layout (see e.g. the CTA analysis vignette)
- [x] plot AOIs by their signal strength (i.e. the quantile or housekeeper normalization factor) vs. background (the neg control factor). 
- [x] Compute a blue-grey-red color vector based on AOIs' ratios of signal strength / background. I.e. higher background AOIs are more blue, while higher signal AOIs are more red. 
- [x] Draw PCA plots colored by the above vector, colored by slide ID, by AOI type, and by other user-defined variables.

**Comment by NicoleEO** [comment]
Background subtract and plots previously included. Plots available through workflows.
