### ISSUE TITLE
Reading DCCs

### ISSUE THREAD

**Issue by pdichiaro** [Nanostring-Biostats/GeomxTools#48]
readNanoStringGeomxSet () to read DCCs created with GeoMx® NGS Pipeline gives this error:

 Error: invalid version specification ‘DRAGEN_GeoMx_3.7.4-49’

![Screenshot 2021-05-26 at 19 39 42](https://user-images.githubusercontent.com/50377927/119706328-214d9a00-be5a-11eb-840b-4311c36707b5.png)

**Comment by NicoleEO** [comment]
Fixed here: https://github.com/Nanostring-Biostats/GeomxTools/tree/iss40-dcc-version
Let me know if it works, and I will merge into dev.
thanks @pdichiaro

**Comment by pdichiaro** [comment]
@NicoleEO It does not work. Same error.

you can download one of my samples from here https://we.tl/t-4bmR4PKdel to test your code.

**Comment by NicoleEO** [comment]
@pdichiaro this seemed to require changes beyond the one error. I have added some new edits to that branch I sent earlier and this should be merged with dev soon.

**Comment by NicoleEO** [comment]
@pdichiaro this has now been merged in dev. Let us know if you run into any additional issues.

**Comment by NicoleEO** [comment]
This solved readDCCFile issue, but there is one more edit regarding mismatch dimensions in readNanoStringGeoMxSet

**Comment by pdichiaro** [comment]
Using readNanoStringGeoMxSet:  
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

**Comment by rvitancol** [comment]
@pdichiaro 
I was able to reproduce the error you are getting when I specify a protocolDataColNames in the 
readNanoStringGeoMxSet function that is not part of the annotation file.  You can try and run see if it works.
<pre><code>readNanoStringGeoMxSet(dccFiles = DCCFiles,
                       pkcFiles = PKCFiles,
                       phenoDataFile = SampleAnnotationFile,
                       phenoDataSheet = "Template",
                       phenoDataDccColName = "Sample_ID"))
</code></pre>
 Then if you need to put columns in your annotation file on the protocol data slot, then you can specify these columns in the protocolData parameter

<pre><code>
demoData2 <-
  suppressWarnings(readNanoStringGeoMxSet(dccFiles = DCCFiles,
                                          pkcFiles = PKCFiles,
                                          phenoDataFile = SampleAnnotationFile,
                                          phenoDataSheet = "Template",
                                          phenoDataDccColName = "Sample_ID",
                                          protocolDataColNames =  c("roi", "aoi")))
</code></pre>

Let me know if this works, if not I can further investigate this.

**Comment by pdichiaro** [comment]
@rvitancol no, it does not work...same error 
Error in .rowNamesDF<-(x, value = value) : invalid 'row.names' length

**Comment by rvitancol** [comment]
@pdichiaro are you using the code in the dev branch?

**Comment by pdichiaro** [comment]
@rvitancol you were right. In the dev branch your code works!! Thanks.
Do you know how to convert probe IDs into gene names ? If I checked the expression using assayData(demoData)[["exprs"]] I still see the probe IDs as row.names.

**Comment by rvitancol** [comment]
@pdichiaro you can use aggregateCounts function to collapse to target. 

# collapse to targets
target_demoData <- aggregateCounts(demoData)
dim(target_demoData)
exprs(target_demoData)[1:5, 1:5]

**Comment by pdichiaro** [comment]
perfect. Thanks

**Comment by rvitancol** [comment]
Closing this issue. Already resolved in dev.
