### ISSUE TITLE
User vignette

### ISSUE THREAD

**Issue by NicoleEO** [Nanostring-Biostats/GeomxTools#53]
The intro vignette is great for people familiar with the expression set structure. Suggest adding a vignette for someone reading in their data for the first time into a structure such as this. One that explains each section that needs to be replaced with the user's own path or column names.

- [x] Need to reference GeoDiff as alternative method for QC/DE path
- [x] Before QC is performed counts should be shifted to match DA outputs with function shiftCountsOne and DALogic=TRUE

**Comment by rvitancol** [comment]
Merged to dev, waiting for feedback from Cx
