### ISSUE TITLE
'rmarkdown' package should be installed and declared as a dependency of the 'GeomxTools' package

### ISSUE THREAD

**Issue by stegemang** [Nanostring-Biostats/GeomxTools#61]
I am having a hard time getting GeomxTools working on a fresh install of R 4.1.0
Here is the error I just encountered.
```

Error: Failed to install 'GeomxTools' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> --- re-building 'Introduction.Rmd' using rmarkdown
E> Error: processing vignette 'Introduction.Rmd' failed with diagnostics:
E> The 'rmarkdown' package should be installed and declared as a dependency of the 'GeomxTools' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
E> --- failed re-building 'Introduction.Rmd'

```

![image](https://user-images.githubusercontent.com/8881477/121423554-40056380-c925-11eb-8058-3dbf0d319a22.png)

**Comment by NicoleEO** [comment]
Best way to install and load dev branch

>devtools::install_github("https://github.com/Nanostring-Biostats/GeomxTools/", ref="dev")
>library("GeomxTools", lib.loc="<user path install put package in listed in the output from install>")
