### ISSUE TITLE
GeoMx Normalization

### ISSUE THREAD

**Issue by pdichiaro** [Nanostring-Biostats/GeomxTools#69]
target_demoData = normalize(target_demoData , data_type="RNA", norm_method="quant", desiredQuantile = .9, toElt = "q_norm")

Why do you suggest desiredQuantile = .9 ? I know GeoMx recommends to use Q3 for normalization. 

How to plot boxplot using autoplot as normalisation plot ?

**Comment by NicoleEO** [comment]
@pdichiaro if you would like to do Q3 normalization, change desiredQuantile = 0.75. For assay related questions such as best practices, please email: geomxsupport@nanostring.com.

The autoplot functionality does not include this plot at this time. However, you can view/extract data from the GeoMxSet object and plot with these outputs through the normal R plotting methods. For example, if you access the output from your normalized code as seen below, this provides you with a matrix that you can use for plotting.
countsMatrix <- assayDataElement(target_demoData, elt="q_norm")
