### ISSUE TITLE
QC: Local Grubbs Outlier flags have different types

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/GeomxTools#79]
Some of them has logical and some are characters
![image](https://user-images.githubusercontent.com/55164869/124331722-a8222080-db44-11eb-8959-0f8a22968803.png)

**Comment by NicoleEO** [comment]
@rvitancol and @yuqiren I am starting to rethink this. It should be a consistent type. I will update to just say TRUE instead of low and high. Is that OK?

**Comment by NicoleEO** [comment]
Updated in dev now with TRUE, should have a consistent type now.
