### ISSUE TITLE
negGeoMean and negGeoSD returned as same value from aggregateCounts 

### ISSUE THREAD

**Issue by JasonWReeves** [Nanostring-Biostats/GeomxTools#92]
After running aggregateCounts(...) negative geometric mean & sd values are stored as the same value in the two columns:
![image](https://user-images.githubusercontent.com/42476184/127049732-56b86cdd-4058-4ea5-94ed-f51ea60132e4.png)

All values in the columns are equal when testing:
`all(pData(target_demoData)[['NegGeoMean_TAP_H_WTA_v1.0']] == pData(target_demoData)[['NegGeoSD_TAP_H_WTA_v1.0']])
`

**Comment by NicoleEO** [comment]
It was hardcoded in the apply to geomean. I've fixed this. 
![image](https://user-images.githubusercontent.com/20404635/129291285-4a751721-7625-4abe-b686-f8e4afeedd18.png)
