### ISSUE TITLE
readNanoStringGeoMxSet produces an error when reading in DCCs from different software versions

### ISSUE THREAD

**Issue by tylerhether** [Nanostring-Biostats/GeomxTools#94]
When pulling in DCC files from multiple software versions, the protocol data are comprised of different column names and lengths. This causes an error when doing `rbind` in the block below.

https://github.com/Nanostring-Biostats/GeomxTools/blob/3bf10a302756599155425d50be4a7666c1f6c5f9/R/readNanoStringGeoMxSet.R#L182-L187

A quick solution here might be to use `dplyr::bind_rows` instead.

**Comment by NicoleEO** [comment]
@tylerhether I misinterpreted your request. I was thinking you were trying to bind two different object data. Your change makes sense, if you want and still have time feel free to PR. If not, just let me know seems like a quick fix.

**Comment by tylerhether** [comment]
No problem. I'll submit a PR shortly.
